### ISSUE TITLE
Ensure Lats are South

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/eapi-api#5]
The trick here is, we need to make sure our script is providing the Lats (south) properly to the script but we also need to make sure the NCL processing script is consuming them the right way.

I don't know offhand if we need to make the lats negative for South or not.  (i.e. 10S = -10N).

**Comment by BobTorgerson** [comment]
All of the latitudes are in degrees N, so 0-90 is north of the equator and 0 to -90 are south of the equator in this application. We have modified the output text for the returned results to show latitude in degrees N and longitude in degrees E to match the ingested data. This is done in #6
